
-- ----------------------------
-- Table structure for GEN_TABLE_COLUMN_ORACLE
-- ----------------------------
DROP TABLE "LANE"."GEN_TABLE_COLUMN_ORACLE";
CREATE TABLE "LANE"."GEN_TABLE_COLUMN_ORACLE" (
  "COLUMN_ID" NUMBER(20,0) VISIBLE NOT NULL,
  "TABLE_ID" NUMBER(20,0) VISIBLE,
  "COLUMN_NAME" NVARCHAR2(200) VISIBLE,
  "COLUMN_COMMENT" NVARCHAR2(500) VISIBLE,
  "COLUMN_TYPE" NVARCHAR2(100) VISIBLE,
  "JAVA_TYPE" NVARCHAR2(500) VISIBLE,
  "JAVA_FIELD" NVARCHAR2(200) VISIBLE,
  "IS_PK" NCHAR(1) VISIBLE,
  "IS_INCREMENT" NCHAR(1) VISIBLE,
  "IS_REQUIRED" NCHAR(1) VISIBLE,
  "IS_INSERT" NCHAR(1) VISIBLE,
  "IS_EDIT" NCHAR(1) VISIBLE,
  "IS_LIST" NCHAR(1) VISIBLE,
  "IS_QUERY" NCHAR(1) VISIBLE,
  "QUERY_TYPE" NVARCHAR2(200) VISIBLE,
  "HTML_TYPE" NVARCHAR2(200) VISIBLE,
  "DICT_TYPE" NVARCHAR2(200) VISIBLE,
  "SORT" NUMBER(11,0) VISIBLE,
  "CREATE_BY" NVARCHAR2(64) VISIBLE,
  "CREATE_TIME" DATE VISIBLE,
  "UPDATE_BY" NVARCHAR2(64) VISIBLE,
  "UPDATE_TIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."COLUMN_ID" IS '编号';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."TABLE_ID" IS '归属表编号';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."COLUMN_NAME" IS '列名称';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."COLUMN_COMMENT" IS '列描述';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."COLUMN_TYPE" IS '列类型';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."JAVA_TYPE" IS 'JAVA类型';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."JAVA_FIELD" IS 'JAVA字段名';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."IS_PK" IS '是否主键（1是）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."IS_INCREMENT" IS '是否自增（1是）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."IS_REQUIRED" IS '是否必填（1是）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."IS_INSERT" IS '是否为插入字段（1是）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."IS_EDIT" IS '是否编辑字段（1是）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."IS_LIST" IS '是否列表字段（1是）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."IS_QUERY" IS '是否查询字段（1是）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."QUERY_TYPE" IS '查询方式（等于、不等于、大于、小于、范围）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."HTML_TYPE" IS '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."DICT_TYPE" IS '字典类型';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."SORT" IS '排序';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "LANE"."GEN_TABLE_COLUMN_ORACLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON TABLE "LANE"."GEN_TABLE_COLUMN_ORACLE" IS '代码生成业务表字段';

-- ----------------------------
-- Primary Key structure for table GEN_TABLE_COLUMN_ORACLE
-- ----------------------------
ALTER TABLE "LANE"."GEN_TABLE_COLUMN_ORACLE" ADD CONSTRAINT "SYS_C0070224" PRIMARY KEY ("COLUMN_ID");

-- ----------------------------
-- Checks structure for table GEN_TABLE_COLUMN_ORACLE
-- ----------------------------
ALTER TABLE "LANE"."GEN_TABLE_COLUMN_ORACLE" ADD CONSTRAINT "SYS_C0070221" CHECK ("COLUMN_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
